nohup build/nr-ue -c config/free5gc-ue-0.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-1.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-2.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-3.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-4.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-5.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-6.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-7.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-8.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-9.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-10.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-11.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-12.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-13.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-14.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-15.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-16.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-17.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-18.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-19.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-20.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-21.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-22.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-23.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-24.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-25.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-26.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-27.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-28.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-29.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-30.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-31.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-32.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-33.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-34.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-35.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-36.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-37.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-38.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-39.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-40.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-41.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-42.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-43.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-44.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-45.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-46.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-47.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-48.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-49.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-50.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-51.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-52.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-53.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-54.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-55.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-56.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-57.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-58.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-59.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-60.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-61.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-62.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-63.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-64.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-65.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-66.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-67.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-68.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-69.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-70.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-71.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-72.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-73.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-74.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-75.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-76.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-77.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-78.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-79.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-80.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-81.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-82.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-83.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-84.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-85.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-86.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-87.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-88.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-89.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-90.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-91.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-92.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-93.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-94.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-95.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-96.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-97.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-98.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-99.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-100.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-101.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-102.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-103.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-104.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-105.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-106.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-107.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-108.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-109.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-110.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-111.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-112.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-113.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-114.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-115.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-116.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-117.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-118.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-119.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-120.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-121.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-122.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-123.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-124.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-125.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-126.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-127.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-128.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-129.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-130.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-131.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-132.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-133.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-134.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-135.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-136.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-137.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-138.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-139.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-140.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-141.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-142.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-143.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-144.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-145.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-146.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-147.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-148.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-149.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-150.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-151.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-152.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-153.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-154.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-155.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-156.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-157.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-158.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-159.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-160.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-161.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-162.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-163.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-164.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-165.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-166.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-167.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-168.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-169.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-170.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-171.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-172.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-173.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-174.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-175.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-176.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-177.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-178.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-179.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-180.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-181.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-182.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-183.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-184.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-185.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-186.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-187.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-188.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-189.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-190.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-191.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-192.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-193.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-194.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-195.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-196.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-197.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-198.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-199.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-200.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-201.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-202.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-203.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-204.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-205.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-206.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-207.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-208.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-209.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-210.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-211.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-212.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-213.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-214.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-215.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-216.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-217.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-218.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-219.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-220.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-221.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-222.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-223.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-224.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-225.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-226.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-227.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-228.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-229.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-230.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-231.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-232.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-233.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-234.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-235.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-236.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-237.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-238.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-239.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-240.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-241.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-242.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-243.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-244.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-245.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-246.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-247.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-248.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-249.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-250.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-251.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-252.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-253.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-254.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-255.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-256.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-257.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-258.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-259.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-260.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-261.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-262.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-263.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-264.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-265.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-266.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-267.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-268.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-269.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-270.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-271.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-272.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-273.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-274.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-275.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-276.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-277.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-278.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-279.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-280.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-281.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-282.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-283.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-284.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-285.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-286.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-287.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-288.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-289.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-290.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-291.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-292.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-293.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-294.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-295.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-296.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-297.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-298.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-299.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-300.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-301.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-302.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-303.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-304.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-305.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-306.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-307.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-308.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-309.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-310.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-311.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-312.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-313.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-314.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-315.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-316.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-317.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-318.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-319.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-320.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-321.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-322.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-323.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-324.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-325.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-326.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-327.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-328.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-329.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-330.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-331.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-332.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-333.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-334.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-335.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-336.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-337.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-338.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-339.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-340.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-341.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-342.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-343.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-344.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-345.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-346.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-347.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-348.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-349.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-350.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-351.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-352.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-353.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-354.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-355.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-356.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-357.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-358.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-359.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-360.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-361.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-362.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-363.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-364.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-365.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-366.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-367.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-368.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-369.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-370.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-371.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-372.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-373.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-374.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-375.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-376.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-377.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-378.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-379.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-380.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-381.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-382.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-383.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-384.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-385.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-386.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-387.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-388.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-389.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-390.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-391.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-392.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-393.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-394.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-395.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-396.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-397.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-398.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-399.yaml >/dev/null 2>&1 &
wait
echo "执行结束"
