nohup build/nr-ue -c config/free5gc-ue-0.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-1.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-2.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-3.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-4.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-5.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-6.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-7.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-8.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-9.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-10.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-11.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-12.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-13.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-14.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-15.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-16.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-17.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-18.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-19.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-20.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-21.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-22.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-23.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-24.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-25.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-26.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-27.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-28.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-29.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-30.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-31.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-32.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-33.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-34.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-35.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-36.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-37.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-38.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-39.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-40.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-41.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-42.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-43.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-44.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-45.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-46.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-47.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-48.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-49.yaml >/dev/null 2>&1 &
wait
echo "执行结束"
