nohup build/nr-ue -c config/free5gc-ue-0.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-1.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-2.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-3.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-4.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-5.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-6.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-7.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-8.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-9.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-10.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-11.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-12.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-13.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-14.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-15.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-16.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-17.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-18.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-19.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-20.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-21.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-22.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-23.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-24.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-25.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-26.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-27.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-28.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-29.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-30.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-31.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-32.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-33.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-34.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-35.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-36.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-37.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-38.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-39.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-40.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-41.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-42.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-43.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-44.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-45.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-46.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-47.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-48.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-49.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-50.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-51.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-52.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-53.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-54.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-55.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-56.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-57.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-58.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-59.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-60.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-61.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-62.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-63.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-64.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-65.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-66.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-67.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-68.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-69.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-70.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-71.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-72.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-73.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-74.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-75.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-76.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-77.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-78.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-79.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-80.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-81.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-82.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-83.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-84.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-85.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-86.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-87.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-88.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-89.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-90.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-91.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-92.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-93.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-94.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-95.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-96.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-97.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-98.yaml >/dev/null 2>&1 &
nohup build/nr-ue -c config/free5gc-ue-99.yaml >/dev/null 2>&1 &
wait
echo "执行结束"
